theme = "hugo-assembly"
baseURL = ""
languageCode = "en-US"
title = "TopCofounder"

# Metadata
[params]
  author = "Russell Rosario"
  description = "Networking for elite entrepreneurs"

# banner section (from here on is for assembly theme)
[params.banner]
  title = "Networking for elite entrepreneurs"
  byline = "Exclusive membership by application only"

[params.actions] # CTAs
  enable = true
  register = "CTA Now!"

# Navigation section
[params.nav]
  home = "Home"
  about = "About"
  join = "Join"
  contact = "Contact Us"

# Join section
[params.join]
  enable = true
  title = "Join TopCofounder"
  subtitle = "Want to be a part of an exclusive networking group?"

  [[params.join.item]]
    weight = "mailto:apply@topcofounder.com"
    description = "Looking to join a startup? We will connect you with the right opportunities! Apply with your resume and a quick description of what you are looking for."
    button_item_info = "Apply"

  [[params.join.item]]
    weight = "mailto:pitch@topcofounder.com"
    description = "Have a business idea but need some help? Pitch us your idea and we'll notify members in our network that might be interested in joining you."
    button_item_info = "Pitch"




# About section
[params.about]
  enable = true
  title = "About TopCofounder"
  subtitle = "Finding a talented cofounder is a hard task. We're here to help."
  description = "We are a matchmaking service dedicated to helping you find elite talent. Our membership at the moment comprises <strong>100+ entrepreneurs</strong> across the globe with a variety of skills including Business Development, Marketing, Sales, Information Technology, and Fundraising. <br><br> Membership is based on a variety of criteria and our acceptance rate is currently less than 5%. We do this to ensure the quality of our group. TopCofounder is actively seeking new applicants as well as hearing business proposals so apply now!"
  button_text = "Apply Now"

# Contact section
[params.contact]
  enable = true
  title = "Get In Touch"
  message = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."
  name_placeholder = "Your name"
  email_placeholder = "Your email"
  email_disclaimer = "We'll never share your email with anyone else."
  message_placeholder = "Please enter a message."
  button_text = "Submit"

# Footer section
[params.footer]
  enable = true
  copy = "&copy; TopCofounder | All rights reserved."
  twitter = "topcofounder"
  facebook = ""
  instagram = ""

